version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    container_name: php-app
    volumes:
      - .:${APP_DIR}
    working_dir: ${APP_DIR}
    tty: true

  sonar-scanner:
    build:
      context: .
      dockerfile: docker/sonar-scanner/Dockerfile
      args:
        SONAR_SCANNER_VERSION: ${SONAR_SCANNER_VERSION}
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    container_name: app-sonar-scanner
    volumes:
      - .:${APP_DIR}
    env_file:
      - .env
    working_dir: ${APP_DIR}
    environment:
      SONAR_SCANNER_OPTS: "${SONAR_SCANNER_OPTS}"
    entrypoint: [ "/entrypoint.sh" ]
