version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: php-app
    volumes:
      - .:/home/dev/app
    working_dir: /home/dev/app
    tty: true
